### ISSUE TITLE
老哥你的题库怎么不支持自主搜题啊，比其他同类的稳多了，很多都搜到了答案

### ISSUE THREAD

**Issue by nidajia** [lyj0309/eWorkAssis#2]
求开发！支持付费http://cdn.zjx666.top/search.html

**Comment by lyj0309** [comment]
已经更新了
2333.pub

**Comment by lyj0309** [comment]
已经更新了
[2333.pub](http://2333.pub)

**Comment by nidajia** [comment]
真的稳！！！！🙌没有人 👐比fake大哥 ☝️更懂 👌做题!!!,希望日后有捐赠渠道，支持
