### ISSUE TITLE
你好，能不能让脚本支持限时的课堂答题

### ISSUE THREAD

**Issue by quewn** [lyj0309/eWorkAssis#6]
https://mobilelearn.chaoxing.com/page/quiz/stu/studentQuestion
这个网址
![1](https://user-images.githubusercontent.com/36659407/155455867-10419f9a-1797-44a6-8dfa-1f88f1e6fc79.png)

**Comment by lyj0309** [comment]
可以先使用网页或者小程序查题 
<https://ti.fakev.cn>
